function variables = translateToEnglish(variables)
	choicesPortuguese = {'Tempo',
	'Altitude',
	'Velocidade vertical',
	'Aceleração vertical',
	'Velocidade total',
	'Aceleração total',
	'Posição a favor do vento',
	'Posição paralela ao vento',
	'Distância lateral',
	'Direção lateral',
	'Velocidade lateral',
	'Aceleração lateral',
	'Latitude',
	'Longitude',
	'Aceleração gravitacional',
	'Ângulo de ataque',
	'Taxa de rotação',
	'Taxa de arremesso',
	'Taxa de guinada',
	'Massa.',
	'Massa do propelente',
	'Momento de inércia longitudinal ',
	'Momento de inércia de rotação',
	'Localização do CP',
	'Localização do CG',
	'Calibres da margem de estabilidade',
	'Número de Mach',
	'Número de Reynolds',
	'Impulso',
	'Força de arrasto',
	'Coeficiente de arrasto',
	'Coeficiente de arrasto axial',
	'Coeficiente de arrasto de atrito',
	'Coeficiente de arrasto de pressão',
	'Coeficiente de arrasto de base',
	'Coeficiente de força normal',
	'Coeficiente de momento de Pitch',
	'Guinada coeficiente de momento',
	'Coeficiente de força lateral',
	'Coeficiente do momento de rotação',
	'Coeficiente forçado de rotação',
	'Coeficiente de amortecimento de rotação',
	'Coeficiente de arremesso de amortecimento',
	'Aceleração de Coriolis',
	'Comprimento de referência',
	'Área de referência',
	'Orientação vertical (zênite)',
	'Orientação lateral (azimute)',
	'Velocidade do vento',
	'Temperatura do ar',
	'Pressão do ar',
	'Velocidade do som',
	'Passo de tempo de simulação',
	'Tempo de computação'};
	
	choicesEnglish = {'Time',
	'Altitude',
	'Vertical velocity',
	'Vertical acceleration',
	'Total velocity',
	'Total acceleration',
	'Position East of launch',
	'Position North of launch',
	'Lateral distance',
	'Lateral direction',
	'Lateral velocity',
	'Lateral acceleration',
	'Latitude',
	'Longitude',
	'Gravitational acceleration',
	'Angle of attack',
	'Roll rate',
	'Pitch rate',
	'Yaw rate',
	'Mass',
	'Propellant mass',
	'Longitudinal moment of inertia',
	'Rotational moment of inertia',
	'CP location',
	'CG location',
	'Stability margin calibers',
	'Mach number',
	'Reynolds number',
	'Thrust',
	'Drag force',
	'Drag coefficient',
	'Axial drag coefficient',
	'Friction drag coefficient',
	'Pressure drag coefficient',
	'Base drag coefficient',
	'Normal force coefficient',
	'Pitch moment coefficient',
	'Yaw moment coefficient',
	'Side force coefficient',
	'Roll moment coefficient',
	'Roll forcing coefficient',
	'Roll damping coefficient',
	'Pitch damping coefficient',
	'Coriolis acceleration',
	'Reference length',
	'Reference area',
	'Vertical orientation (zenith)',
	'Lateral orientation (azimuth)',
	'Wind velocity',
	'Air temperature',
	'Air pressure',
	'Speed of sound',
	'Simulation time step',
	'Computation time'};
	
	for i = [1:length(choicesPortuguese)]
		variables(strcmp(variables, choicesPortuguese(i))) = choicesEnglish(i);
	end
end